name: flutterbackgroundsync
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #utils
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  url_launcher: ^6.2.5
  
  #firebase and background sync
  cloud_firestore: ^4.16.0
  flutter_background_service: ^5.0.5
  device_info_plus: ^10.0.1
  flutter_local_notifications: ^17.0.0
  #layout  
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_easyloading: ^3.0.5

  
 #packages
  package_architecture: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_architecture.git
  package_firebase: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_firebase.git
      ref: 0.0.2
  package_module: 
    git:
      url: https://github.com/NandoPimenta/flutter_package_module.git      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: 
  rename: ^3.0.1


flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:


  uses-material-design: true

